# Generated by Django 2.2.5 on 2020-01-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examusersession',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
