# Generated by Django 2.2.5 on 2019-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20190925_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='question',
            name='sub_category',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
