# Generated by Django 2.2.5 on 2020-12-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='price',
            new_name='percent',
        ),
    ]
