# Generated by Django 2.2.5 on 2020-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20201230_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=False, help_text='Active status of current coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(help_text='coupon name', max_length=150, unique=True),
        ),
    ]
