# Generated by Django 2.2.5 on 2019-11-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191103_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', help_text='surname of the user', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', help_text='username of the user', max_length=254),
            preserve_default=False,
        ),
    ]
