# Generated by Django 2.2.5 on 2020-12-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_stripe_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
