# Generated by Django 2.2.5 on 2021-01-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201229_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.CharField(blank=True, help_text='Enter the card stripe id', max_length=250, null=True),
        ),
    ]
