# Generated by Django 2.2.5 on 2021-01-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='card',
            new_name='card_id',
        ),
        migrations.AddField(
            model_name='user',
            name='credit_card_number',
            field=models.CharField(blank=True, help_text='Enter the credit card last four digits', max_length=250, null=True),
        ),
    ]
