# Generated by Django 2.2.5 on 2020-02-11 05:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('4actuaries sites', '0003_auto_20200211_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/techstriker/workspace/e-learning/app/../assets/img'), upload_to='static/img/'),
        ),
    ]
