# Generated by Django 2.2.5 on 2020-02-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uploading', '0005_auto_20200212_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadMedia',
            new_name='UploadSlide',
        ),
    ]
