# Generated by Django 2.2.5 on 2020-03-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uploading', '0007_auto_20200214_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadslide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
    ]
