# Generated by Django 2.2.5 on 2019-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', editable=False, max_length=255)),
                ('time_limit', models.IntegerField(default=0)),
                ('n_questions', models.PositiveIntegerField(default=5)),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('exam_type', models.CharField(choices=[('exam', 'Exam'), ('elearning', 'E-learning'), ('elearning_ns', 'E-learning (no slides)')], default='exam', max_length=15)),
            ],
        ),
    ]
