# Generated by Django 2.2.5 on 2019-11-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
