# Generated by Django 2.2.5 on 2019-11-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('elearning', 'E-learning')], default='exam', max_length=15),
        ),
    ]
