# Generated by Django 2.2.5 on 2019-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20191115_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=254)),
                ('sub_category', models.CharField(max_length=254)),
                ('figure', models.CharField(default='n', max_length=254)),
                ('content', models.CharField(blank=True, max_length=254)),
                ('explanation', models.CharField(blank=True, max_length=254)),
                ('correct', models.CharField(blank=True, max_length=254)),
                ('answer1', models.CharField(blank=True, max_length=254)),
                ('answer2', models.CharField(blank=True, max_length=254)),
                ('answer3', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
