# Generated by Django 2.2.5 on 2019-11-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20191117_0406'),
        ('exam', '0003_exam_show_answers'),
    ]

    operations = [
    ]
