# Generated by Django 2.2.5 on 2019-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20191118_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexportexam',
            name='answer1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportexam',
            name='answer2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportexam',
            name='answer3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportexam',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportexam',
            name='correct',
            field=models.TextField(blank=True),
        ),
    ]
