# Generated by Django 2.2.5 on 2019-09-26 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0003_auto_20190926_1332'),
        ('exam', '0002_exam_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearning',
            fields=[
                ('exam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exam.Exam')),
                ('slides', models.BooleanField(default=False)),
                ('random_questions', models.BooleanField(default=True)),
            ],
            bases=('exam.exam',),
        ),
        migrations.CreateModel(
            name='ELearningSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0)),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='elearning.ELearning')),
                ('questions', models.ManyToManyField(blank=True, to='question.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearning')),
            ],
        ),
        migrations.CreateModel(
            name='ELearningUserSession',
            fields=[
                ('examusersession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.ExamUserSession')),
                ('seen_slides', models.PositiveIntegerField(default=0)),
                ('active_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearningSession')),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearning')),
            ],
            bases=('question.examusersession',),
        ),
        migrations.CreateModel(
            name='ELearningUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='elearning.ELearningUserSession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='elearningsession',
            name='slides',
            field=models.ManyToManyField(blank=True, to='elearning.Slide'),
        ),
        migrations.CreateModel(
            name='ELearningRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('repeat_after', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearningUserSession')),
            ],
        ),
        migrations.CreateModel(
            name='ELearningCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearningUserSession')),
            ],
        ),
    ]
