# Generated by Django 2.2.5 on 2019-11-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportExportELearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=254)),
                ('sub_category', models.CharField(max_length=254)),
                ('figure', models.CharField(default='n', max_length=254)),
                ('content', models.CharField(blank=True, max_length=254)),
                ('explanation', models.CharField(blank=True, max_length=254)),
                ('correct', models.CharField(blank=True, max_length=254)),
                ('answer1', models.CharField(blank=True, max_length=254)),
                ('answer2', models.CharField(blank=True, max_length=254)),
                ('answer3', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elearning.ELearning')),
            ],
        ),
        migrations.CreateModel(
            name='ELearningUserSession',
            fields=[
                ('examusersession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.ExamUserSession')),
                ('seen_slides', models.PositiveIntegerField(default=0)),
                ('phase', models.IntegerField(choices=[(0, 'Corrections'), (1, 'Repetitions'), (2, 'New Questions'), (3, 'Slides')], default=2)),
                ('active_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearningSession')),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearning')),
            ],
            bases=('question.examusersession',),
        ),
        migrations.AddField(
            model_name='elearninguseranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Answer'),
        ),
        migrations.AddField(
            model_name='elearninguseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
        migrations.AddField(
            model_name='elearninguseranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='elearning.ELearningUserSession'),
        ),
    ]
