# Generated by Django 2.2.5 on 2019-12-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='topic of the presentation', max_length=500)),
                ('slide', models.ImageField(upload_to='presentation/')),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearning')),
            ],
        ),
    ]
