# Generated by Django 2.2.5 on 2019-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_elearninguseranswer_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningrepetition',
            name='repeat_after',
            field=models.DateField(),
        ),
    ]
