# Generated by Django 2.2.5 on 2019-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='slide',
            field=models.CharField(help_text='name of the slide', max_length=1000),
        ),
    ]
