# Generated by Django 2.2.5 on 2019-11-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20191103_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningusersession',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Corrections'), (1, 'Repetitions'), (2, 'New Questions'), (3, 'Slides')], default=2),
        ),
    ]
