# Generated by Django 2.2.5 on 2019-11-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20191119_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elearning',
            name='memory_force',
        ),
        migrations.AddField(
            model_name='elearningusersession',
            name='memory_force',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=100),
        ),
    ]
