# Generated by Django 2.2.5 on 2019-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_auto_20191216_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearninguseranswer',
            name='phase',
            field=models.CharField(default='new_questions', max_length=254),
        ),
    ]
