# Generated by Django 2.2.5 on 2019-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_elearningusersession_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningrepetition',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
