# Generated by Django 2.2.5 on 2020-01-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_elearninguseranswer_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
