# Generated by Django 2.2.5 on 2020-01-28 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_presentation_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearningsession',
            name='elearning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='elearning.ELearning'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='elearning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.ELearning'),
        ),
    ]
