# Generated by Django 2.2.5 on 2019-11-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_importexportelearning'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexportelearning',
            name='figure',
            field=models.CharField(default='n', max_length=254),
        ),
        migrations.AlterField(
            model_name='elearningsession',
            name='elearning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='elearning.ELearning'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='elearning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elearning.ELearning'),
        ),
    ]
