# Generated by Django 2.2.5 on 2019-11-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20191116_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearning',
            name='certificate_count',
            field=models.PositiveSmallIntegerField(default=369),
        ),
    ]
