# Generated by Django 2.2.5 on 2020-02-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20200128_0601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
