# Generated by Django 2.2.5 on 2019-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20191116_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexportelearning',
            name='answer1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportelearning',
            name='answer2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportelearning',
            name='answer3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportelearning',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportelearning',
            name='correct',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='importexportelearning',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
