# Generated by Django 2.2.5 on 2020-12-24 04:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the plan', max_length=255)),
                ('price', models.FloatField(help_text="Specify one time price of the price (per interval). If plan is monthly provide 1 month price, if it's yearly provide 1 year or 12 month price")),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration')),
                ('interval', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=100)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], help_text='In which currency you want to pay.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Admin toggle to display/hide the plan from the user')),
            ],
            options={
                'verbose_name': 'Subscription_Plan',
                'verbose_name_plural': 'Subscription_Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('active', models.BooleanField(default=False, help_text='The active subscription of the user')),
                ('transaction_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscription.SubscriptionPlan')),
                ('user', models.ForeignKey(help_text='User related to subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Events Log Activity', null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('subscription_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ActivityLog',
                'verbose_name_plural': 'ActivityLogs',
            },
        ),
    ]
