# Generated by Django 2.2.5 on 2020-12-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_id',
            field=models.CharField(default=0, help_text='Enter the stripe plan id', max_length=150),
            preserve_default=False,
        ),
    ]
