# Generated by Django 2.2.5 on 2020-12-29 04:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='response_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Response data', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Date', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(help_text='Description Log'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='End Date', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='event',
            field=models.CharField(blank=True, help_text='Events Log Activity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
