# Generated by Django 2.2.5 on 2020-12-29 12:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20201229_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Subscription cancelled'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='transaction_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(help_text='User related to subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
