# Generated by Django 2.2.5 on 2020-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20201229_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='transaction_details',
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELLED', 'CANCELLED'), ('HALTED', 'HALTED'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', help_text='The status subscription of the user', max_length=150),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subs_id',
            field=models.CharField(blank=True, help_text='Subscription id of stripe', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration',
            field=models.DateField(),
        ),
    ]
