# Generated by Django 2.2.5 on 2021-01-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20210104_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
    ]
