# Generated by Django 2.2.5 on 2021-01-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_remove_activitylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount_paid',
            field=models.FloatField(blank=True, help_text='Amount paid for the subscription plan.', null=True),
        ),
    ]
