# Generated by Django 2.2.5 on 2021-01-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_coupon_expiry'),
        ('subscription', '0009_subscription_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.Coupon'),
        ),
    ]
