# Generated by Django 2.2.5 on 2021-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscription_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_id',
            field=models.CharField(blank=True, help_text='Enter the card stripe id', max_length=250, null=True),
        ),
    ]
